drop table if exists transactions;
drop table if exists accounts;
drop table if exists client_projections;

create table client_projections (
    client_id varchar(50) primary key,
    name varchar(120) not null,
    identification varchar(40) not null,
    active boolean not null
);

create table accounts (
    id bigint generated by default as identity primary key,
    account_number varchar(30) not null unique,
    account_type varchar(40) not null,
    initial_balance numeric(19, 2) not null,
    current_balance numeric(19, 2) not null,
    active boolean not null,
    client_id varchar(50) not null
);

create table transactions (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    date timestamp with time zone not null,
    transaction_type varchar(40) not null,
    amount numeric(19, 2) not null,
    balance numeric(19, 2) not null,
    constraint fk_transactions_account foreign key (account_id) references accounts(id)
);
